import pandas as pd

pd.options.display.float_format = "{:,.2f}".format
pd.set_option("display.width", 150)
pd.set_option("display.max_columns", None)


# ==========================================================
# Constants
# ==========================================================

PROCESSED_FOLDER = "data/processed"


# ==========================================================
# Loading Functions
# ==========================================================

def load_order_items():
    """
    Load cleaned order items.
    """

    return pd.read_csv(
        f"{PROCESSED_FOLDER}/order_items.csv"
    )


def load_products():
    """
    Load cleaned products dataset.
    """

    return pd.read_csv(
        f"{PROCESSED_FOLDER}/products.csv"
    )


def load_customers():
    """
    Load cleaned customers dataset.
    """

    return pd.read_csv(
        f"{PROCESSED_FOLDER}/customers.csv"
    )


def load_orders():
    """
    Load cleaned orders dataset.
    """

    return pd.read_csv(
        f"{PROCESSED_FOLDER}/orders.csv"
    )


# ==========================================================
# Helper Functions
# ==========================================================

def add_revenue_column(df):
    """
    Return a dataframe with a Revenue column.
    """

    df = df.copy()

    if "Revenue" not in df.columns:
        df["Revenue"] = (
            df["quantity"]
            * df["unit_price"]
            * (1 - df["discount_percent"] / 100)
        )

    return df


def print_report(dataframe):
    """
    Print a report DataFrame with extra spacing
    between columns for better readability.
    """

    print(
        dataframe.reset_index().to_string(
            index=False,
            col_space=18,
        )
    )


def save_report(dataframe, filename):
    """
    Save a report DataFrame to the reports folder.
    """

    dataframe.to_csv(
        f"reports/{filename}",
        index=True
    )

    print(f"✓ Saved: reports/{filename}")


# ==========================================================
# Analysis Functions
# ==========================================================

def top_revenue_products(analysis_df):
    """
    Find the top 10 products by total revenue.
    """

    top_products = (
        analysis_df.groupby("product_name")["Revenue"]
        .sum()
        .sort_values(ascending=False)
        .head(10)
    )

    return top_products


def revenue_by_region(analysis_df):
    """
    Calculate revenue
    generated by each region.
    """

    region_revenue = (
        analysis_df.groupby("region")["Revenue"]
        .sum()
        .sort_values(ascending=False)
    )

    return region_revenue


def revenue_by_segment(analysis_df):
    """
    Calculate revenue generated
    by each customer segment.
    """

    segment_revenue = (
        analysis_df.groupby("segment")["Revenue"]
        .sum()
        .sort_values(ascending=False)
    )

    return segment_revenue


def discount_analysis(analysis_df):
    """
    Analyze revenue by
    discount percentage.
    """

    discount_revenue = (
        analysis_df.groupby("discount_percent")
        .agg(
            Total_Revenue=("Revenue", "sum"),
            Total_Orders=("order_id", "count"),
            Average_Revenue=("Revenue", "mean")
        )
        .sort_index()
    )

    return discount_revenue


def revenue_by_sales_channel(analysis_df):
    """
    Analyze revenue generated
    by each sales channel.
    """

    channel_revenue = (
        analysis_df.groupby("sales_channel")
        .agg(
            Total_Revenue=("Revenue", "sum"),
            Total_Orders=("order_id", "count"),
            Average_Order_Value=("Revenue", "mean")
        )
        .sort_values(
            by="Total_Revenue",
            ascending=False
        )
    )

    return channel_revenue


def monthly_revenue_trend(analysis_df):
    """
    Calculate monthly revenue trend.
    """

    analysis_df = analysis_df.copy()

    analysis_df["order_date"] = pd.to_datetime(
        analysis_df["order_date"]
    )

    analysis_df["Year_Month"] = (
        analysis_df["order_date"]
        .dt.to_period("M")
        .astype(str)
    )

    monthly_revenue = (
        analysis_df.groupby("Year_Month")
        .agg(
            Total_Revenue=("Revenue", "sum"),
            Total_Orders=("order_id", "count"),
            Average_Order_Value=("Revenue", "mean")
        )
        .sort_index()
    )

    return monthly_revenue


# ==========================================================
# Main
# ==========================================================

def main():

    order_items = load_order_items()
    products = load_products()
    customers = load_customers()
    orders = load_orders()

    order_items = add_revenue_column(order_items)

    print(f"\nTotal Revenue : {order_items['Revenue'].sum():,.2f}")

    # Build the master analysis dataset once
    analysis_df = (
        order_items
        .merge(products, on="product_id")
        .merge(orders, on="order_id")
        .merge(customers, on="customer_id")
    )

    top_products = top_revenue_products(analysis_df)
    print("\n=== Top 10 Products by Revenue ===")
    print_report(top_products)
    save_report(top_products, "top_products.csv")

    region_revenue = revenue_by_region(analysis_df)
    print("\n=== Revenue by Region ===")
    print_report(region_revenue)
    save_report(region_revenue, "revenue_by_region.csv")

    segment_revenue = revenue_by_segment(analysis_df)
    print("\n=== Revenue by Customer Segment ===")
    print_report(segment_revenue)
    save_report(segment_revenue, "revenue_by_segment.csv")

    discount_report = discount_analysis(analysis_df)
    print("\n=== Discount Analysis ===")
    print_report(discount_report)
    save_report(discount_report, "discount_analysis.csv")

    channel_report = revenue_by_sales_channel(analysis_df)
    print("\n=== Sales Channel Analysis ===")
    print_report(channel_report)
    save_report(channel_report, "sales_channel_analysis.csv")

    monthly_report = monthly_revenue_trend(analysis_df)
    print("\n=== Monthly Revenue Trend ===")
    print_report(monthly_report)
    save_report(monthly_report, "monthly_revenue_trend.csv")

    best_month = monthly_report["Total_Revenue"].idxmax()
    best_revenue = monthly_report.loc[best_month, "Total_Revenue"]

    print(f"\nBest Performing Month: {best_month}")
    print(f"Revenue: ₹{best_revenue:,.2f}")


if __name__ == "__main__":
    main()